// Employees
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';
export const EMPLOYEE_LOGIN = 'EMPLOYEE_LOGIN';
export const EMPLOYEELOGIN_SUCCESS = 'EMPLOYEELOGIN_SUCCESS';
export const EMPLOYEELOGIN_ERROR = 'EMPLOYEELOGIN_ERROR';
export const EMPLOYEE_ENDSESION = 'EMPLOYEE_ENDSESION';

export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//Pacientes == Users

export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
