// Employees
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';
export const EMPLOYEELOGIN_SUCCESS = 'EMPLOYEELOGIN_SUCCESS';
export const EMPLOYEELOGIN_ERROR = 'EMPLOYEELOGIN_ERROR';
export const EMPLOYEE_ENDSESION = 'EMPLOYEE_ENDSESION';
